📌 Comprehensive Pandas Interview Guide
This guide is split into:
1️⃣ Basic Pandas Concepts – Fundamentals
2️⃣ Intermediate Pandas Concepts – Performance & Efficiency
3️⃣ Advanced Pandas Concepts – Quant & Trading Applications
4️⃣ Pandas Coding Challenges – Interview-style problems
5️⃣ Optimization Tips – Best practices for speed & memory efficiency
6️⃣ Mock Test with Solutions – Hands-on practice

🔹 1️⃣ Basic Pandas Concepts
These are must-know fundamentals for working with Pandas in finance.

📍 1.1 What is Pandas? Why is it useful in finance?
Pandas is a Python library for data analysis and manipulation, widely used in finance for:

Time-series analysis (e.g., stock prices, trading volume)
Data cleaning & transformation (e.g., handling missing data, reformatting)
Performance metrics & statistics (e.g., calculating returns, PnL)

📍 1.2 Key Data Structures in Pandas
Structure	Description
Series	    1D labeled array (like a column in Excel)
DataFrame	2D labeled data table (like a SQL table or Excel sheet)

📍 1.3 Loading Data from CSV

In [5]:
df = pd.read_csv("trades.csv")
df.head()

,symbol,ISIN,Trade Price,Quantity Long,Quantity Short,Buy Sell,source,theo
0,AAPL,US0378331005,150.5,100.0,NaN,BUY,ELK,151
1,AAPL,US0378331005,149.8,NaN,50.0,SELL,CF,150
2,GOOG,US02079K3059,2800.2,30.0,NaN,BUY,ELK,2805
3,GOOG,US02079K3059,2795.6,NaN,20.0,SELL,CF,2798
4,TSLA,US88160R1014,700.1,40.0,NaN,BUY,ELK,702

📍 1.4 Selecting Rows & Columns

In [6]:
# Select column
df['Trade Price']

# Select multiple columns
df[['Trade Price', 'ISIN']]

# Select first 5 rows
df.head(5)

# Select based on condition
df[df['Trade Price'] > 100]

,symbol,ISIN,Trade Price,Quantity Long,Quantity Short,Buy Sell,source,theo
0,AAPL,US0378331005,150.5,100.0,NaN,BUY,ELK,151
1,AAPL,US0378331005,149.8,NaN,50.0,SELL,CF,150
2,GOOG,US02079K3059,2800.2,30.0,NaN,BUY,ELK,2805
3,GOOG,US02079K3059,2795.6,NaN,20.0,SELL,CF,2798
4,TSLA,US88160R1014,700.1,40.0,NaN,BUY,ELK,702
5,TSLA,US88160R1014,698.4,NaN,30.0,SELL,CF,699

🔹 2️⃣ Intermediate Pandas Concepts

📍 2.1 Grouping & Aggregation (Common in PnL Reporting)

In [8]:
df.groupby('symbol')['theo'].sum()

symbol
AAPL     301
GOOG    5603
TSLA    1401
Name: theo, dtype: int64

📍 2.2 Sorting Data

In [9]:
df.sort_values(by='Trade Price', ascending=False)

,symbol,ISIN,Trade Price,Quantity Long,Quantity Short,Buy Sell,source,theo
2,GOOG,US02079K3059,2800.2,30.0,NaN,BUY,ELK,2805
3,GOOG,US02079K3059,2795.6,NaN,20.0,SELL,CF,2798
4,TSLA,US88160R1014,700.1,40.0,NaN,BUY,ELK,702
5,TSLA,US88160R1014,698.4,NaN,30.0,SELL,CF,699
0,AAPL,US0378331005,150.5,100.0,NaN,BUY,ELK,151
1,AAPL,US0378331005,149.8,NaN,50.0,SELL,CF,150

📍 2.3 Handling Missing Data

In [6]:
df.fillna(0)  # Fill NaN with 0
df.dropna()   # Remove rows with NaN

   Price  Volume
0    100      10
1    200       5
2    300      20

📍 2.4 Merge & Join (Used for Combining Trading Data)

In [10]:
df1 = pd.DataFrame({'symbol': ['AAPL', 'GOOG'], 'price': [150, 2800]})
df2 = pd.DataFrame({'symbol': ['AAPL', 'GOOG'], 'volume': [100, 50]})

merged = pd.merge(df1, df2, on='symbol')

In [9]:
merged

  symbol  price  volume
0   AAPL    150     100
1   GOOG   2800      50

🔹 3️⃣ Advanced Pandas Concepts

📍 3.1 Vectorization (Avoiding Loops for Speed)

In [10]:
df['PnL'] = df['Trade Price'] * df['Quantity']

KeyError: 'Trade Price'

📍 3.2 Rolling & Expanding Windows (For Moving Averages & Volatility)

In [ ]:
df['Moving_Avg'] = df['Price'].rolling(window=5).mean()

🔹 4️⃣ Pandas Coding Challenges (Interview-Style)

In [19]:
import pandas as pd

# Creating the clearing_firm_trades DataFrame
clearing_firm_trades = pd.DataFrame([
    {"symbol": "AAPL", "ISIN": "US0378331005", "Trade Price": 150.5, "Quantity Long": 100, "Quantity Short": None, "Buy Sell": "BUY", "source": "ELK", "theo": 151},
    {"symbol": "AAPL", "ISIN": "US0378331005", "Trade Price": 149.8, "Quantity Long": None, "Quantity Short": 50, "Buy Sell": "SELL", "source": "CF", "theo": 150},
    {"symbol": "GOOG", "ISIN": "US02079K3059", "Trade Price": 2800.2, "Quantity Long": 30, "Quantity Short": None, "Buy Sell": "BUY", "source": "ELK", "theo": 2805},
    {"symbol": "GOOG", "ISIN": "US02079K3059", "Trade Price": 2795.6, "Quantity Long": None, "Quantity Short": 20, "Buy Sell": "SELL", "source": "CF", "theo": 2798},
    {"symbol": "TSLA", "ISIN": "US88160R1014", "Trade Price": 700.1, "Quantity Long": 40, "Quantity Short": None, "Buy Sell": "BUY", "source": "ELK", "theo": 702},
    {"symbol": "TSLA", "ISIN": "US88160R1014", "Trade Price": 698.4, "Quantity Long": None, "Quantity Short": 30, "Buy Sell": "SELL", "source": "CF", "theo": 699},
    {"symbol": "TSLA", "ISIN": "US88160R1014", "Trade Price": 698.4, "Quantity Long": None, "Quantity Short": 30, "Buy Sell": "SELL", "source": "CF", "theo": 699},
    {"symbol": "TSLA", "ISIN": "US88160R1014", "Trade Price": 698.4, "Quantity Long": None, "Quantity Short": 30, "Buy Sell": "SELL", "source": "CF", "theo": 699},
    {"symbol": "META", "ISIN": "US98160R1014", "Trade Price":700, "Quantity Long": None, "Quantity Short": 200, "Buy Sell": "SELL", "source": "CF", "theo": 699}
])

# Display DataFrame
print(clearing_firm_trades)

  symbol          ISIN  Trade Price  Quantity Long  Quantity Short Buy Sell  \
0   AAPL  US0378331005        150.5          100.0             NaN      BUY
1   AAPL  US0378331005        149.8            NaN            50.0     SELL
2   GOOG  US02079K3059       2800.2           30.0             NaN      BUY
3   GOOG  US02079K3059       2795.6            NaN            20.0     SELL
4   TSLA  US88160R1014        700.1           40.0             NaN      BUY
5   TSLA  US88160R1014        698.4            NaN            30.0     SELL
6   TSLA  US88160R1014        698.4            NaN            30.0     SELL
7   TSLA  US88160R1014        698.4            NaN            30.0     SELL
8   META  US98160R1014        700.0            NaN           200.0     SELL

  source  theo
0    ELK   151
1     CF   150
2    ELK  2805
3     CF  2798
4    ELK   702
5     CF   699
6     CF   699
7     CF   699
8     CF   699

4.1 Find the Top 3 Most Traded Stocks

In [21]:
import numpy as np
clearing_firm_trades['volume'] = np.where(clearing_firm_trades['Buy Sell']=='BUY', clearing_firm_trades['Quantity Long'], clearing_firm_trades['Quantity Short'])

In [22]:
volume_by_symbol = clearing_firm_trades.groupby('symbol')['volume'].sum()

In [26]:
volume_by_symbol_no_index = volume_by_symbol.reset_index(name='volume_count')

In [24]:
volume_by_symbol.nlargest(3)

symbol
META    200.0
AAPL    150.0
TSLA    130.0
Name: volume, dtype: float64

In [29]:
volume_by_symbol_no_index.nlargest(3,"volume_count")

  symbol  volume_count
2   META         200.0
0   AAPL         150.0
3   TSLA         130.0

4.3 Find Stocks That Traded Above Their 10-day Moving Average

In [ ]:
df['10 Day avg']=df['Price'].rolling(window=10).mean()
df[df['Price'] > df['10 Day avg']]

In [30]:
import pandas as pd
import numpy as np

# Create a DataFrame with repetitive string values
df = pd.DataFrame({
    'symbol': ['AAPL', 'GOOG', 'TSLA', 'AAPL', 'TSLA', 'GOOG', 'AAPL'],
    'sector': ['Tech', 'Tech', 'Auto', 'Tech', 'Auto', 'Tech', 'Tech']
})

# Default memory usage (before converting to category)
print(df.info())  

# Convert 'symbol' and 'sector' to category dtype
df['symbol'] = df['symbol'].astype('category')
df['sector'] = df['sector'].astype('category')

# Reduced memory usage (after conversion)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   symbol  7 non-null      object
 1   sector  7 non-null      object
dtypes: object(2)
memory usage: 240.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   symbol  7 non-null      category
 1   sector  7 non-null      category
dtypes: category(2)
memory usage: 398.0 bytes
None

In [31]:
import numpy as np
import time

# Create a large DataFrame
df_large = pd.DataFrame({
    'Trade Price': np.random.randint(90, 110, size=1_000_000),
    'theo': np.random.randint(95, 115, size=1_000_000)
})

# Using apply() (Slow)
start = time.time()
df_large['price_diff_apply'] = df_large.apply(lambda row: row['theo'] - row['Trade Price'], axis=1)
print("Apply() Time:", time.time() - start)

# Using vectorized operation (Fast)
start = time.time()
df_large['price_diff_vectorized'] = df_large['theo'] - df_large['Trade Price']
print("Vectorized Time:", time.time() - start)

Apply() Time: 15.777985095977783
Vectorized Time: 0.004997968673706055

In [33]:
df_large['price_diff_vectorized'] = df_large['theo'] - df_large['Trade Price']

In [37]:
import pandas as pd

# Reduce the number of periods
df = pd.DataFrame(
    index=pd.date_range("2022-01-01", periods=100000, freq="T"),  # 100K rows, not 1M
    data={"price": range(100000)}
)
print(df.head())


%timeit df.loc["2022-01-10"]
%timeit df.iloc[9]

                     price
2022-01-01 00:00:00      0
2022-01-01 00:01:00      1
2022-01-01 00:02:00      2
2022-01-01 00:03:00      3
2022-01-01 00:04:00      4
855 µs ± 107 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
92.7 µs ± 4.44 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [40]:
df.loc["2022-01-10"]

                     price
2022-01-10 00:00:00  12960
2022-01-10 00:01:00  12961
2022-01-10 00:02:00  12962
2022-01-10 00:03:00  12963
2022-01-10 00:04:00  12964
...                    ...
2022-01-10 23:55:00  14395
2022-01-10 23:56:00  14396
2022-01-10 23:57:00  14397
2022-01-10 23:58:00  14398
2022-01-10 23:59:00  14399

[1440 rows x 1 columns]

1️⃣ What is a "View"?
A view means the sliced data still references the original DataFrame.
Any changes to the view will modify the original data.

In [91]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': np.arange(5), 'B': np.arange(5, 10)})
view_df = df[:3]  # Slicing without .copy() -> Possible View

view_df.loc[0, 'A'] = 100  # May modify df

# copy_df = df.loc[:3]
# df.loc[0, 'A'] = 100

c:\Users\hgao6\miniconda3\envs\stock_env2\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
c:\Users\hgao6\miniconda3\envs\stock_env2\lib\site-packages\pandas\core\indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [93]:
view_df._is_view

True

In [61]:
df = pd.DataFrame({'A': np.arange(5), 'B': np.arange(5, 10)})
view_df = df[:3]  # Slicing without .copy() -> Possible View

In [73]:
view_df._is_view

True

In [65]:
view_df.loc[0, "A"] = 100

c:\Users\hgao6\miniconda3\envs\stock_env2\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
c:\Users\hgao6\miniconda3\envs\stock_env2\lib\site-packages\pandas\core\indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [68]:
view_df

     A  B
0  100  5
1    1  6
2    2  7

2️⃣ What is a "Copy"?
A copy is an independent DataFrame that doesn't share memory with the original.

In [70]:
df = pd.DataFrame({'A': np.arange(5), 'B': np.arange(5, 10)})

copy_df = df[:3].copy()  # ✅ Explicitly creating a copy

copy_df.loc[0, 'A'] = 100  # Won't affect df

print(df)  # ✅ Original df is unchanged!

   A  B
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [76]:
copy_df.flags

In [72]:
id(copy_df)

2369469475328